---
title: "Kavin Siaw"
subtitle: "My Data Science Portfolio"
# use quarto markdown to 
---

# About Me

I am a Physics major with minors in Mathematics and Computer Programming, specializing in  in astronomy, signal processing, and scientific research. I am also interest in data science to find meaningful insights from data and understand their trends.

I enjoy transforming noisy, complex datasets into clear insights through visualization, modeling, and careful analysis.

## Resume

My resume has recently been updated with my latest research, technical experience, and leadership roles. Feel free to explore it to learn more about my background and qualifications.

## Projects

This portfolio highlights my projects in data cleansing, exploratory analysis, storytelling, and machine learning, built using Quarto, SQL, and Lets-Plot. Use the menu above to browse each section and view the full projects.

<!-- [MarkDown Basics](https://quarto.org/docs/authoring/markdown-basics.html#links-images) -->
